// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNgam5se3dHLQw8yhKrEb6W0FMhiHS1E',
    appId: '1:114088269593:web:614633d905dd810f175788',
    messagingSenderId: '114088269593',
    projectId: 'work-timer-2dab6',
    authDomain: 'work-timer-2dab6.firebaseapp.com',
    storageBucket: 'work-timer-2dab6.firebasestorage.app',
    measurementId: 'G-LBQC7K96VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdqvURqLS1om26gRcGkvzOQmzhxU9dUw',
    appId: '1:114088269593:android:d4bc87b510c79f94175788',
    messagingSenderId: '114088269593',
    projectId: 'work-timer-2dab6',
    storageBucket: 'work-timer-2dab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEmRimp4IArY7iKUUAZmItpnYC6u0pRI',
    appId: '1:114088269593:ios:d67427370f6a1dd4175788',
    messagingSenderId: '114088269593',
    projectId: 'work-timer-2dab6',
    storageBucket: 'work-timer-2dab6.firebasestorage.app',
    iosBundleId: 'com.worktimer.workTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEmRimp4IArY7iKUUAZmItpnYC6u0pRI',
    appId: '1:114088269593:ios:d67427370f6a1dd4175788',
    messagingSenderId: '114088269593',
    projectId: 'work-timer-2dab6',
    storageBucket: 'work-timer-2dab6.firebasestorage.app',
    iosBundleId: 'com.worktimer.workTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPNgam5se3dHLQw8yhKrEb6W0FMhiHS1E',
    appId: '1:114088269593:web:131b76b985d3c803175788',
    messagingSenderId: '114088269593',
    projectId: 'work-timer-2dab6',
    authDomain: 'work-timer-2dab6.firebaseapp.com',
    storageBucket: 'work-timer-2dab6.firebasestorage.app',
    measurementId: 'G-6NL84D04G9',
  );
}
